### PR TITLE
Add formatter

### PR DESCRIPTION
**Pull request by ryanhausen**
This PR adds the ruff formatter to the project.

### CODE REVIEW

**Review by amitschang — APPROVED** [review]

**Comment by jamienoss** [comment]
@ryanhausen thanks for doing this. I can take it from here though so that we don't merge this until after some larger existing PRs are merged to reduce significant conflict resolution.

**Review by jamienoss — DISMISSED** [review]
Approving but let's hold off on merging this for now, please, thanks.

**Comment by amitschang** [comment]
@jamienoss ok, I will cease and desist. Another way is just to merge in (ignoring failures) the config parts of this. But I'll leave it to you

**Comment by jamienoss** [comment]
@amitschang Yep, we could merge in the formatted infra without the format changes, turn off the test, and then redo the broad formatting at a later time, but that's almost the same as holding off on this for a mo.

**Comment by jamienoss** [comment]
@amitschang I've rebased and rerun the formater. Ready for review again please, cheers.

Also, you cool with this getting merged now? I still have some PRs open that may be a pita to rebase but at least #73 is merged as that would have been very painful.

**Review by amitschang — APPROVED** [review]
Sure, I think it can go now. The formatting is automatable, so should not be too problematic

**Comment by jamienoss** [comment]
>The formatting is automatable, so should not be too problematic

For sure, we can trivially run it for the new PRs to have them pass the new style test. I meant more about all of the changes introduced by this PR will cause conflicts with existing open PRs when rebasing.

**Pull request merged**
